# Margaret Li
# 4/20/22
# Compares refined arabidopsis proteome files generated by ML and KG
# The purpose is to make sure that the files are the same

# get generated files and read their lines into separate lists
file_ML = open("C:\\Users\\jli\\plantproteomes\\SeqComparison\\scripts\\refined_arabidopsis.fasta", "r")
file_KG = open("C:\\Users\\jli\\plantproteomes\\SeqComparison\\proteomes\\arabidopsis\\AraportUpdated_KG.fasta", "r")

ML_list = file_ML.readlines()
KG_list = file_KG.readlines()

# corroborate lengths of files
print("Number of lines for ML and KG respectively:")
print(len(ML_list))
print(len(KG_list))

# print first lines of each file
# the 8 is there to keep track of spacing
print("8" + ML_list[0] + "8")
print("8" + KG_list[0] + "8")

# check on a line-by-line basis to see if files match
for i in range(0 , len(ML_list)):
    if ML_list[i] == KG_list[i]:
        print("all clear!")
    else:
        print("ERROR: line " + str(i))
        #print(ML_list[i])    