#!/bin/env python3

import pandas as pd
import re
from Bio import SeqIO

# new dataframe  create 3 columns identfier, description, and Sequence column
df = pd.DataFrame(columns=['Identifier', 'Description', "Sequence"])


filename = r'C:\Users\kesha\mitochondrion.2.fasta'
with open(filename) as infile:

    print(f"INFO: Reading {filename}")
    for record in SeqIO.parse(infile, 'fasta'):
        sequence = str(record.seq)
        match = re.match(r'^(.+?)\s+(.*)$', record.description)

        if match:
            identifier = match.group(1)
            description = match.group(2)
            new_row = {'Identifier': match.group(
                1), 'Description': match.group(2), 'Sequence': sequence}
            df = df.append(new_row, ignore_index=True)

        else:
            print(
                f"ERROR: Unable to parse description line: {record.description}")
            exit()
        print(f"{identifier} - {description}")


# total number of entries within the file
index = df.index
number_of_rows = len(index)
print("Total reads: %i" % number_of_rows)

# total number of repeated identifiers(Listed out in a pivot table with each individual Identifier)
print(df.pivot_table(columns=['Identifier'], aggfunc='size'))
# total number of repeated descriptions(Listed out in a pivot table with each individual Description)
print(df.pivot_table(columns=['Description'], aggfunc='size'))
# total number of repeated descriptions(Listed out in a pivot table with each individual Sequence)
print(df.pivot_table(columns=['Sequence'], aggfunc='size'))
